In [1]:
# Import list...

import numpy as np

# Extra Exercises: Functions

#### 1. is_a_vowel

Initialize a "vowels" string object containing all the vowels of the alphabet. Then, write a function that checks whether the input is a vowel. Your function should return "True" if the input is a vowel, and "False" otherwise.

In [2]:
vowels = "aeiouy"

def is_a_vowel(c):
    """
    Function that checks whether c is a vowel or not, where
    c: string (unicharacter)
    """
    # Make sure it still works even if c is capitalized...
    c = c.lower()  # ... Turn c into lowercase!
    
    if c in vowels:
        return True
    
    return False
    
print(is_a_vowel('a'))
print(is_a_vowel('b'))
print(is_a_vowel('E'))
print(is_a_vowel('Z'))

True
False
True
False


#### 2. count_vowels

Write a function that takes a string as input and returns the number of vowels it contains.

In [3]:
def count_vowels(s):
    """
    Function that takes as input a string s and returns the number of vowels it contains, where:
    s: string
    """
    counter = 0
    for i in s:
        if is_a_vowel(i):
            counter += 1
    
    return counter

print(count_vowels("hello"))
print(count_vowels("The quick brown fox jumps over the lazy dog"))
print(count_vowels("AEIOUY, ce sont les voyelles de l'alphabet!"))

2
12
17


#### 3. count_occurences

Write a function that takes as input a string $s$ and a character $c$. The function should return how many times $c$ appears in $s$.

In [4]:
def count_occurences(s, c):
    """
    Function that returns how many times c appears in s, where
    c: string (unicharacter)
    s: string
    """
    counter = 0
    for i in s:
        if i == c:
            counter += 1
            
    return counter
    
print(count_occurences("hello", "l"))
print(count_occurences("She sells seashells by the seashore", "s"))
print(count_occurences("Les chemises de l'archiduchesse sont-elles seches ou archi seches?", "c"))

2
7
6


#### 4. print_multiples

Write a function that takes as input integers $n$ and $m$ and prints out $m$ multiples of $n$, starting from $n$. For example, print_multiples(n=5, m=4) should print the following:

5\
10\
15\
20

In [5]:
def print_multiples(n, m, verbose=False):
    """
    Function that prints out m multiples of n, starting from n, where:
    n: integer
    m: integer
    """
    mults = []
    for i in range(1, m+1):
        if verbose:
            print(n*i)
        mults.append(n*i)
        
    return mults
    
print_multiples(5, 4, verbose=True)

5
10
15
20


[5, 10, 15, 20]

#### 5. print_mult_table

Write a function that takes as input $rows$ and $columns$ and prints out a multiplication table with the required number of rows and columns. For example, print_mult_table(rows=3, columns=3) should print:

1  2  3

2  4  6

3  6  9

(Hint: use the function you wrote in exercise 4)

In [6]:
def print_mult_table(rows, cols):
    """
    Function that prints out a multiplication with the given number of rows and columns, where
    rows: integer
    cols: integer
    """
    table = []
    
    for i in range(1, rows+1):
        
        table.append(print_multiples(i, cols))
        
    print(np.asarray(table))
    
print_mult_table(3, 5)
print("\n")  # The \n character is a linebreak
print_mult_table(6, 7)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]


[[ 1  2  3  4  5  6  7]
 [ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]]


#### 6. increase_by_index

Write a function that takes as input a list of integers and increases the value of each element in the list by its index. For example, increase_by_index([1, 2, 3, 4, 5]) should return:

[1, 3, 5, 7, 9]

In [7]:
def increase_by_index(l):
    """
    Function that increases each element in l by its index, where
    l: list of integers
    """
    new_list = []
    for i in range(len(l)):
        new_list.append(l[i]+i)
    
    return new_list

increase_by_index([1, 2, 3, 4, 5])

[1, 3, 5, 7, 9]

#### 7. get_smallest

Write a function that takes as input a list of integers and returns the smallest one. For example, get_smallest([5, 0, -3, 1, 9]) should return:

-3

In [8]:
def get_smallest(l):
    """
    Function that returns the smallest element in l, where:
    l: list of integers
    """
    
    smallest = l[0]
    for i in l:
        if i < smallest:
            smallest = i
            
    return smallest

get_smallest([3, 0, -3, 5, 1, 9])

-3

#### 8. get_random_list

Write a function that takes as input an integer $n$ and returns a list (or an array) containing $n$ random numbers between 0 and 1. For example, get_random_list(5) might return:

[0.345345, 0.124044, 0.343985, 0.998534, 0.2353458]

(Hint: Use the function $\texttt{numpy.random.random()}$)

In [9]:
def get_random_list(n):
    """
    Generate a list with n randomly generated data points between 0 and 1, where:
    n: integer
    """
    random_list = []
    for i in range(n):
        random_list.append(np.random.random())
        
    return random_list

get_random_list(10)

[0.6356113640316838,
 0.22919552739392834,
 0.17463250627064575,
 0.9024077409203121,
 0.644502151763653,
 0.9317108682202716,
 0.028219005804993036,
 0.11942788008873995,
 0.8457801122511206,
 0.18367225529735676]

#### 9. swap_elements

Write a function that takes as input a list and two integers $i$ and $j$. The function should swap the elements at the $i$th and $j$th index. For example, swap_elements([5, 6, 7, 8], 0, 2) should return:

[7, 6, 5, 8]

In [10]:
def swap_elements(l, i, j):
    """
    Swaps the ith and jth element in l, where:
    l: list
    i: integer (<= length of list)
    j: integer (<= length of list)
    """
    
    ith_element = l[i]
    
    l[i] = l[j]
    l[j] = ith_element
    
    return l

swap_elements([5, 6, 7, 8], 0, 2)

[7, 6, 5, 8]

#### 10. shift_left

Write a function that takes as input a list and shifts each element one to the left. For example, shift_left([1, 2, 3, 4]) should return:

[2, 3, 4, 1]

In [11]:
def shift_left(l):
    """
    Function that shifts each element in l one place to the left, where:
    l: list
    """
    new_list = []
    for i in range(len(l)):
        if i == len(l)-1:
            new_list.append(l[0])
        else:
            new_list.append(l[i+1])
        
    return new_list

shift_left([1, 2, 3, 4])

[2, 3, 4, 1]

#### 11. print_2d_list

Write a function that takes as input a list of lists and prints out each sub-element, one at a time. For example, print_2d_list([[1,2],[3,4]]) should print:

1\
2\
3\
4

In [12]:
def print_2d_list(l):
    """
    Function that prints out each sub-element in a 2D list of lists, where:
    l: list of lists
    """
    
    for i in l:
        for j in i:
            print(j)
            
print_2d_list([[1,2,3],[4,5,6]])

1
2
3
4
5
6


#### 12. What does this function do?

In [13]:
def mystery_function(x):
    s = x/2
    t = s+2
    u = s*10
    return u

mystery_function(10)

50.0

#### 13. What does this function do?

In [14]:
def mystery_function2(x, n):
    s = x**n / n
    return s

mystery_function2(4, 5)

204.8

#### 14. What does this function do?

In [15]:
def mystery_function3(l, n):
    s = []
    for i in l:
        s.append(i*n)
    return s

mystery_function3([1, 2, 3, 4, 5], 5)

[5, 10, 15, 20, 25]

#### 15. What does this function do?

In [16]:
def mystery_function4(s):
    n = ""
    for i in range(1, len(s)+1):
        n += s[-i]
    return n

mystery_function4("Hello World")

'dlroW olleH'

#### 16. What does this function do?

In [17]:
def mystery_function5(l):
    s = ""
    for i in l:
        s += i
        s += " "
    return s

mystery_function5(["Hello", "World", "here", "I", "am"])

'Hello World here I am '

#### 17. What does this function do?

In [18]:
def mystery_function6(s, delim):
    return s.split(delim)

print(mystery_function6("My favourite meal is sushi", delim=" "))
print(mystery_function6("I live at 123, Fake Street, FP, Fake Country, H7D H8L", delim=","))

['My', 'favourite', 'meal', 'is', 'sushi']
['I live at 123', ' Fake Street', ' FP', ' Fake Country', ' H7D H8L']


#### 18. What does this function do?

In [19]:
def mystery_function7(l):
    n = []
    for i in l:
        for j in i:
            n.append(j)
    return n

mystery_function7([[1,2,3],[4,5],[6,7,8]])

[1, 2, 3, 4, 5, 6, 7, 8]